import path from 'node:path'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [react()],

  test: {
    environment: 'jsdom',
    globals: false,
    setupFiles: ['./vitest.setup.ts'],
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      'tests/integration/**',
      'tests/e2e/**',
    ],

    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      reportsDirectory: './coverage/simple',
      // Coverage tracks the source files that are directly exercised by the
      // default Vitest suite. Mocked dependencies such as repositories,
      // Supabase clients, exports, and external services are intentionally
      // excluded from this default coverage scope.
      include: [
        'src/app/api/admin/summary/route.ts',
        'src/app/api/analyses/[analysisId]/overlays/[overlayId]/refreshes/route.ts',
        'src/app/api/analyses/[analysisId]/overlays/[overlayId]/route.ts',
        'src/app/api/analyses/[analysisId]/overlays/route.ts',
        'src/app/api/analyses/[analysisId]/refreshes/route.ts',
        'src/app/api/analyses/[analysisId]/route.ts',
        'src/app/api/analyses/reorder/route.ts',
        'src/app/api/auth/callback/route.ts',
        'src/app/api/health/route.ts',
        'src/app/api/keyword-batch/route.ts',
        'src/app/api/keywords/[keywordId]/analyses/route.ts',
        'src/app/api/keywords/[keywordId]/overlays/[overlayId]/route.ts',
        'src/app/api/keywords/[keywordId]/overlays/route.ts',
        'src/app/api/keywords/[keywordId]/refreshes/route.ts',
        'src/app/api/keywords/[keywordId]/route.ts',
        'src/app/api/keywords/reorder/route.ts',
        'src/app/api/keywords/route.ts',
        'src/app/api/searches/[id]/refreshes/route.ts',
        'src/app/api/searches/[id]/route.ts',
        'src/app/api/searches/route.ts',
        'src/app/api/stock-data/route.ts',
        'src/app/api/stocks/[ticker]/route.ts',
        'src/app/api/stocks/search/route.ts',
        'src/app/api/trends-internal/route.ts',
        'src/app/api/trends/route.ts',
        'src/components/admin/admin-dashboard-client.tsx',
        'src/components/auth/login-button.tsx',
        'src/components/auth/login-form.tsx',
        'src/components/auth/set-password-form.tsx',
        'src/components/auth/signup-form.tsx',
        'src/components/auth/user-menu.tsx',
        'src/components/keyword/keyword-detail/keyword-detail-client.tsx',
        'src/components/keyword/keyword-detail/keyword-standalone-chart.tsx',
        'src/components/keyword/keyword-detail/overlay-card.tsx',
        'src/components/keyword/keyword-search-page/keyword-search-page-client.tsx',
        'src/components/keyword/keyword-trends/keyword-card.tsx',
        'src/components/keyword/keyword-trends/keyword-index-sidebar.tsx',
        'src/components/keyword/keyword-trends/keyword-search-form.tsx',
        'src/components/keyword/keyword-trends/keyword-search-list.tsx',
        'src/components/keyword/keyword-trends/keyword-trends-chart.tsx',
        'src/components/keyword/keyword-trends/keyword-trends-client.tsx',
        'src/components/keyword/keyword-trends/my-keywords-client.tsx',
        'src/components/keyword/keyword-trends/overlay-manager.tsx',
        'src/components/layout/container.tsx',
        'src/components/layout/header.tsx',
        'src/components/overlays/overlay-detail-client.tsx',
        'src/components/shared/data-table.tsx',
        'src/components/shared/loading-skeleton.tsx',
        'src/components/shared/progress-indicator.tsx',
        'src/components/shared/table-header.tsx',
        'src/components/shared/theme-toggle.tsx',
        'src/components/stock/custom-chart-builder.tsx',
        'src/components/stock/custom-chart-view.tsx',
        'src/components/stock/dashboard-client.tsx',
        'src/components/stock/metrics-card.tsx',
        'src/components/stock/metrics-summary.tsx',
        'src/components/stock/save-stock-button.tsx',
        'src/components/stock/search-form.tsx',
        'src/components/stock/stock-card.tsx',
        'src/components/stock/unified-chart.tsx',
        'src/components/ui/button.tsx',
        'src/lib/calculations.ts',
        'src/lib/fetch-client.ts',
        'src/lib/indicators.ts',
        'src/lib/trends-filter.ts',
        'src/lib/validation.ts',
        'src/lib/utils.ts',
        'src/lib/parsers/trends-parsers.ts',
        'src/lib/utils/currency.ts',
        'src/lib/utils/keyword-classifier.ts',
        'src/lib/utils/keyword-normalization.ts',
        'src/server/admin-auth.ts',
        'src/server/admin-service.ts',
        'src/server/analysis-overlays-service.ts',
        'src/server/cached-stock-service.ts',
        'src/server/health-service.ts',
        'src/server/keyword-analyses-service.ts',
        'src/server/keyword-creation-service.ts',
        'src/server/keyword-overlays-service.ts',
        'src/server/keywords-service.ts',
        'src/server/stock-analysis-service.ts',
        'src/server/stock-refresh-service.ts',
        'src/server/stock-search-service.ts',
        'src/server/trends-internal-service.ts',
      ],
      exclude: [
        'src/**/*.test.ts',
        'src/**/*.test.tsx',
        'src/server/repositories/**',
        'src/lib/constants/**',
        'src/lib/export/**',
        'src/lib/services/**',
        'src/lib/supabase/**',
      ],
    },
  },

  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
})
